# Generated by Django 4.2.11 on 2024-04-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_loginuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
    ]
